#!/bin/bash
# Generate /userdata/p4/config/mediamtx.yml from rtsp.env (always-on pull → local RTSP/WebRTC).
set -euo pipefail
P4_ROOT="${P4_ROOT:-/userdata/p4}"
# shellcheck disable=SC1091
source "${P4_ROOT}/scripts/p4_env.sh"

OUT="${P4_ROOT}/config/mediamtx.yml"
mkdir -p "${P4_ROOT}/config" "${P4_ROOT}/logs"

PROTO="${RTSP_PROTOCOLS:-tcp}"
if [[ "${PROTO}" == "tcp" ]]; then
  TRANSPORT="tcp"
else
  TRANSPORT="udp"
fi

cat >"${OUT}" <<EOF
# Auto-generated by mediamtx_gen_config.sh — do not edit by hand
logLevel: info
logDestinations: [stdout]
readTimeout: 15s
writeTimeout: 15s
rtspAddress: :8554
webrtc: true
webrtcAddress: :8889
webrtcAllowOrigins: ["*"]
webrtcAdditionalHosts: ["${STATIC_IP:-192.168.2.100}", "${RNDIS_IP:-192.168.7.1}"]
paths:
  cam:
    source: ${RTSP_URL}
    rtspTransport: ${TRANSPORT}
    sourceOnDemand: no
EOF

echo "[mediamtx] wrote ${OUT} source=${RTSP_URL} webrtcHost=${STATIC_IP:-192.168.2.100}"
